### PR TITLE
edit Lang

### PR DESCRIPTION
**Pull request by NekoIriyaRu**
edit Lang

### CODE REVIEW

**Comment by HIllya51** [comment]
dont' edit my links.

**Comment by NekoIriyaRu** [comment]
> dont' edit my links.

I'm sorry but you're delusional, what edited links are you talking about?

**Comment by NekoIriyaRu** [comment]
> dont' edit my links.

The lunatranslator.xyz/Resource/game_support link was added based on a message in the Russian translation about an unsupported game.

**Comment by NekoIriyaRu** [comment]
> dont' edit my links.

All I did was add lunatranslator.xyz/Resource/game_support link, translated the name of the services into Russian.

**Pull request closed without merging**
